import 'dart:convert';
import 'dart:typed_data';

import 'package:audio_splitter_app/asp2/control/control_plane.dart';
import 'package:audio_splitter_app/asp2/fec/fec_group.dart';
import 'package:audio_splitter_app/asp2/frame/asp2_frame.dart';
import 'package:audio_splitter_app/asp2/frame/legacy_frame.dart';
import 'package:flutter_test/flutter_test.dart';

/// Phase 8 — protocol fuzzer.
///
/// The plan's gate: "feed random / truncated bytes to `Asp2Frame.decode` +
/// FEC / codec / control decoders, assert graceful drop, never crash". Every
/// decode surface that touches the wire is hammered with malformed, truncated,
/// and bit-flipped input. The contract each surface must honour:
///
///  * [Asp2Frame.decode] — throws **only** [FormatException] on bad input, or
///    returns a frame. Any other thrown type (RangeError, etc.) is a bug.
///  * [LegacyFrameCodec.decode] — never throws; returns null or a frame.
///  * [ControlMessage.tryDecode] — never throws; returns null or a message.
///  * [FecGroup.recover] — never throws; returns null or the recovered shards.
///
/// Input is generated by a **seeded LCG** (glibc constants, same generator as
/// `LossyTransport`), never `Math.random` or the wall clock, so a failing seed
/// reproduces exactly — consistent with the determinism rule across the suite.
class _Lcg {
  int _state;
  _Lcg(int seed) : _state = seed & 0x7fffffff;

  /// Next 31-bit value.
  int next() {
    _state = (1103515245 * _state + 12345) & 0x7fffffff;
    return _state;
  }

  /// Uniform int in [0, bound).
  int nextInt(int bound) => bound <= 1 ? 0 : next() % bound;

  /// A byte buffer of [len] pseudo-random bytes.
  Uint8List bytes(int len) {
    final out = Uint8List(len);
    for (var i = 0; i < len; i++) {
      out[i] = next() & 0xFF;
    }
    return out;
  }
}

/// Build a structurally-valid plaintext ASP-2 frame for mutation seeds.
Uint8List _validFrame(_Lcg rng) {
  final payload = rng.bytes(rng.nextInt(64));
  return Asp2Frame(
    codecId: rng.nextInt(16),
    streamId: rng.nextInt(0x10000),
    sequenceNumber: rng.next(),
    presentationTsUs: rng.next(),
    fecGroupId: rng.nextInt(256),
    fecIndex: rng.nextInt(256),
    payload: payload,
  ).encode();
}

void main() {
  const iterations = 4000;

  group('Fuzz — Asp2Frame.decode', () {
    test('random buffers throw only FormatException, never crash', () {
      final rng = _Lcg(0xA5F00D);
      var decoded = 0, dropped = 0;
      for (var i = 0; i < iterations; i++) {
        final buf = rng.bytes(rng.nextInt(80)); // spans below/above headerSize
        try {
          Asp2Frame.decode(buf);
          decoded++;
        } on FormatException {
          dropped++; // the one allowed failure mode
        } catch (e) {
          fail('Asp2Frame.decode threw ${e.runtimeType} on $buf (not '
              'FormatException): $e');
        }
      }
      expect(decoded + dropped, iterations);
      expect(dropped, greaterThan(0),
          reason: 'fuzz should hit truncated input');
    });

    test('corrupt payload_len never yields RangeError', () {
      final rng = _Lcg(0xBEEF11);
      for (var i = 0; i < iterations; i++) {
        final frame = _validFrame(rng);
        // Stomp the u16 payload_len (offset 16) with an arbitrary value so the
        // declared length disagrees with the buffer; decode must FormatException
        // (truncated) or succeed, never index out of bounds.
        ByteData.view(frame.buffer)
            .setUint16(16, rng.nextInt(0x10000), Endian.little);
        try {
          Asp2Frame.decode(frame);
        } on FormatException {
          // ok
        } catch (e) {
          fail('mutated payload_len threw ${e.runtimeType}: $e');
        }
      }
    });

    test('truncations of a valid frame all drop cleanly', () {
      final rng = _Lcg(0xC0FFEE);
      for (var i = 0; i < 500; i++) {
        final frame = _validFrame(rng);
        final cut = rng.nextInt(frame.length + 1);
        final truncated = Uint8List.sublistView(frame, 0, cut);
        try {
          Asp2Frame.decode(truncated);
        } on FormatException {
          // ok
        } catch (e) {
          fail('truncation to $cut threw ${e.runtimeType}: $e');
        }
      }
    });

    test('decode→encode→decode is stable for accepted frames', () {
      final rng = _Lcg(0x515ABE);
      for (var i = 0; i < 1000; i++) {
        final buf = rng.bytes(20 + rng.nextInt(60));
        Asp2Frame f1;
        try {
          f1 = Asp2Frame.decode(buf);
        } on FormatException {
          continue;
        }
        // A frame the decoder accepted must round-trip its own header fields.
        final f2 = Asp2Frame.decode(f1.encode());
        expect(f2.codecId, f1.codecId);
        expect(f2.streamId, f1.streamId);
        expect(f2.sequenceNumber, f1.sequenceNumber);
        expect(f2.presentationTsUs, f1.presentationTsUs);
        expect(f2.payload, f1.payload);
      }
    });
  });

  group('Fuzz — LegacyFrameCodec.decode', () {
    test('never throws on arbitrary input', () {
      final rng = _Lcg(0x1E6AC9); // any seed
      for (var i = 0; i < iterations; i++) {
        final buf = rng.bytes(rng.nextInt(40));
        LegacyFrame? r;
        expect(() => r = LegacyFrameCodec.decode(buf), returnsNormally);
        if (r != null) expect(r!.payload, isNotEmpty);
      }
    });
  });

  group('Fuzz — ControlMessage.tryDecode', () {
    test('never throws on random strings', () {
      final rng = _Lcg(0xC74111);
      for (var i = 0; i < iterations; i++) {
        // Mix raw random bytes (lossy-decoded to a String) with near-JSON.
        final s = i.isEven
            ? utf8.decode(rng.bytes(rng.nextInt(40)), allowMalformed: true)
            : '{"type":"${rng.nextInt(99)}","data":${rng.nextInt(9)}}';
        expect(() => ControlMessage.tryDecode(s), returnsNormally);
      }
    });

    test('unknown type / missing data are dropped, valid ones survive', () {
      expect(ControlMessage.tryDecode('not json at all'), isNull);
      expect(ControlMessage.tryDecode('[1,2,3]'), isNull); // not an object
      expect(ControlMessage.tryDecode('{"type":"nope","data":{}}'), isNull);
      expect(
          ControlMessage.tryDecode('{"type":"reaction"}'), isNull); // no data
      final ok = ControlMessage.tryDecode('{"type":"zoneRemove","data":'
          '{"zoneId":"main"}}');
      expect(ok, isNotNull);
      expect(ok!.type, ControlMessageType.zoneRemove);
      expect(ok.asZoneRemoveId(), 'main');
    });
  });

  group('Fuzz — FecGroup.recover (hardened receive path)', () {
    test('arbitrary indices / lengths / shardLen never throw', () {
      final rng = _Lcg(0xFEC123);
      var recovered = 0, nulls = 0;
      for (var i = 0; i < iterations; i++) {
        final k = 1 + rng.nextInt(8);
        final m = rng.nextInt(4);
        final group = FecGroup(dataShards: k, parityShards: m);

        // Hostile maps: keys can be out of range / negative, payloads any
        // length, shardLen anything including negative/zero/huge.
        Map<int, Uint8List> randMap(int count) => {
              for (var j = 0; j < count; j++)
                (rng.nextInt(20) - 4): rng.bytes(rng.nextInt(40)),
            };
        final data = randMap(rng.nextInt(k + 2));
        final parity = randMap(rng.nextInt(m + 2));
        final shardLen =
            [-1, 0, 1, rng.nextInt(64), 0x7fffffff][rng.nextInt(5)];

        List<Uint8List>? out;
        expect(
          () => out = group.recover(
            dataByIndex: data,
            parityByIndex: parity,
            shardLen: shardLen,
          ),
          returnsNormally,
          reason: 'k=$k m=$m shardLen=$shardLen data=${data.keys} '
              'parity=${parity.keys}',
        );
        if (out == null) {
          nulls++;
        } else {
          recovered++;
          expect(out!, hasLength(k));
        }
      }
      // The vast majority of random garbage is unrecoverable → null, proving the
      // guards fire rather than throwing.
      expect(nulls, greaterThan(0));
      expect(recovered + nulls, iterations);
    });

    test('a genuinely recoverable group still recovers after fuzzing guards',
        () {
      // Sanity: hardening didn't break the happy path. k=4 m=2, drop 2 data.
      final group = FecGroup(dataShards: 4, parityShards: 2);
      final payloads = [
        Uint8List.fromList([1, 2, 3]),
        Uint8List.fromList([4, 5]),
        Uint8List.fromList([6, 7, 8, 9]),
        Uint8List.fromList([10]),
      ];
      final enc = group.encode(payloads, groupId: 7);
      // Lose data shards 1 and 2; keep data 0,3 and both parity.
      final recovered = group.recover(
        dataByIndex: {0: payloads[0], 3: payloads[3]},
        parityByIndex: {0: enc.parityPayloads[0], 1: enc.parityPayloads[1]},
        shardLen: enc.shardLen,
      );
      expect(recovered, isNotNull);
      expect(recovered![1], payloads[1]);
      expect(recovered[2], payloads[2]);
    });
  });
}
